# Generated by Django 6.0.5 on 2026-08-10 11:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_materialmaster_gst_percentage_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRegistrationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.CharField(max_length=40, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('razorpay_payment_link_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payment_link_url', models.URLField(blank=True, max_length=500)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('linked', 'Linked'), ('failed', 'Failed')], default='created', max_length=20)),
                ('link_sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_payments', to='core.vendor')),
            ],
            options={
                'db_table': 'vendor_registration_payment',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
