# Generated by Django 6.0.5 on 2026-10-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_materialmaster_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkallocation',
            name='completed_mw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='ProjectSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('site_name', models.CharField(max_length=255)),
                ('capacity_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('land_area_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('mounting_type', models.CharField(blank=True, choices=[('ground_fixed', 'Ground mount · fixed tilt'), ('ground_tracker', 'Ground mount · single axis'), ('rooftop', 'Rooftop'), ('floating', 'Floating')], max_length=30)),
                ('village', models.CharField(blank=True, max_length=150)),
                ('tehsil', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('khasra_numbers', models.CharField(blank=True, max_length=255)),
                ('land_title', models.CharField(blank=True, choices=[('allotment', 'Allotment letter · site owner'), ('lease', 'Registered lease deed'), ('freehold', 'Freehold · owned'), ('government', 'Government allotment')], max_length=30)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('tenure_years', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_review', 'In review'), ('cleared', 'Cleared')], default='not_started', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.projectmaster')),
            ],
            options={
                'db_table': 'project_site',
                'ordering': ['site_code'],
            },
        ),
        migrations.CreateModel(
            name='SiteAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(max_length=50)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='site_assessment/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('signed_by', models.CharField(blank=True, max_length=255)),
                ('signed_on', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Awaiting sign-off'), ('cleared', 'Cleared'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.projectsite')),
            ],
            options={
                'db_table': 'site_assessment',
                'ordering': ['display_order', 'id'],
                'unique_together': {('site', 'document_key')},
            },
        ),
    ]
