# Generated by Django 6.0.5 on 2026-10-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_projectworkallocation_completed_mw_projectsite_and_more'),
        ('core', '0005_delete_projectplanner'),
    ]

    operations = [
    ]
