# Generated by Django 6.0.5 on 2026-10-05 10:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_materialmaster_gst_percentage_and_more"),
        (
            "purchase_orders",
            "0006_quotation_client_address_quotation_client_mobile_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoqTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("rooftop", "Open Roof (Rooftop)"),
                            ("ground_mount", "On-Site Solar EPC (Ground-mount)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "solar_boq_template",
                "ordering": ["project_type", "-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComponentSpecSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "module_wp",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("550"), max_digits=8
                    ),
                ),
                ("modules_per_string", models.PositiveIntegerField(default=26)),
                (
                    "inverter_kw",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("125"), max_digits=10
                    ),
                ),
                (
                    "transformer_mva",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("2.5"), max_digits=8
                    ),
                ),
                ("inverters_per_acdb", models.PositiveIntegerField(default=10)),
                (
                    "lv_voltage",
                    models.PositiveIntegerField(
                        default=415, help_text="Low-voltage AC, volts"
                    ),
                ),
                (
                    "ht_voltage_kv",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("11"), max_digits=6
                    ),
                ),
                (
                    "target_dc_ac_ratio",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.200"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "solar_component_spec_set",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="WbsStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_parallel", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "solar_wbs_stage",
                "ordering": ["template", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WbsTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("rooftop", "Open Roof (Rooftop)"),
                            ("ground_mount", "On-Site Solar EPC (Ground-mount)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "solar_wbs_template",
                "ordering": ["project_type", "-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="BoqSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=150)),
                ("is_material", models.BooleanField(default=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="solar_engine.boqtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "solar_boq_section",
                "ordering": ["template", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="BoqTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(max_length=255)),
                ("specification", models.TextField(blank=True)),
                ("unit", models.CharField(default="Nos", max_length=40)),
                (
                    "quantity_basis",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed quantity"),
                            ("per_mw_ac", "Per MW (AC)"),
                            ("per_mwp_dc", "Per MWp (DC)"),
                            ("per_string", "Per string"),
                            ("per_inverter", "Per inverter"),
                            ("per_transformer", "Per transformer"),
                            ("per_acdb", "Per ACDB"),
                            ("per_module", "Per module"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "quantity_factor",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=16
                    ),
                ),
                (
                    "default_material_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "default_labour_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                ("wbs_stage_code", models.CharField(blank=True, max_length=30)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="solar_engine.boqsection",
                    ),
                ),
            ],
            options={
                "db_table": "solar_boq_template_item",
                "ordering": ["section", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("rooftop", "Open Roof (Rooftop)"),
                            ("ground_mount", "On-Site Solar EPC (Ground-mount)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ac_capacity_mw",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "foundation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("driven_pile", "Driven Pile"),
                            ("concrete_pedestal", "Concrete Pedestal"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("locked", "Locked"),
                            ("in_execution", "In Execution"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "boq_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="builds",
                        to="solar_engine.boqtemplate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solar_builds_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solar_builds",
                        to="purchase_orders.quotation",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solar_builds_locked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build",
                        to="core.projectmaster",
                    ),
                ),
                (
                    "spec_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="builds",
                        to="solar_engine.componentspecset",
                    ),
                ),
                (
                    "wbs_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="builds",
                        to="solar_engine.wbstemplate",
                    ),
                ),
            ],
            options={
                "db_table": "solar_project_build",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectBoqItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=150)),
                ("section_order", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(max_length=255)),
                ("specification", models.TextField(blank=True)),
                ("unit", models.CharField(default="Nos", max_length=40)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "material_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "labour_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                ("is_material", models.BooleanField(default=True)),
                (
                    "source_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="solar_engine.boqtemplateitem",
                    ),
                ),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boq_items",
                        to="solar_engine.projectbuild",
                    ),
                ),
            ],
            options={
                "db_table": "solar_project_boq_item",
                "ordering": ["build", "section_order", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSizing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dc_capacity_mwp",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("module_count", models.PositiveIntegerField(default=0)),
                ("string_count", models.PositiveIntegerField(default=0)),
                ("inverter_count", models.PositiveIntegerField(default=0)),
                ("transformer_count", models.PositiveIntegerField(default=0)),
                ("acdb_count", models.PositiveIntegerField(default=0)),
                (
                    "dc_ac_ratio",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "build",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizing",
                        to="solar_engine.projectbuild",
                    ),
                ),
            ],
            options={
                "db_table": "solar_project_sizing",
            },
        ),
        migrations.CreateModel(
            name="ProjectStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_parallel", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_end", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateField(blank=True, null=True)),
                ("actual_end", models.DateField(blank=True, null=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="solar_engine.projectbuild",
                    ),
                ),
                (
                    "source_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="solar_engine.wbsstage",
                    ),
                ),
            ],
            options={
                "db_table": "solar_project_stage",
                "ordering": ["build", "order", "id"],
            },
        ),
        migrations.AddField(
            model_name="wbsstage",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="solar_engine.wbstemplate",
            ),
        ),
        migrations.CreateModel(
            name="WbsWorkPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                ("discipline", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                (
                    "core_workpackage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solar_wbs_packages",
                        to="core.workpackage",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_packages",
                        to="solar_engine.wbsstage",
                    ),
                ),
            ],
            options={
                "db_table": "solar_wbs_work_package",
                "ordering": ["stage", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectWorkPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                ("discipline", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solar_work_packages",
                        to="core.projectworkallocation",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_packages",
                        to="solar_engine.projectstage",
                    ),
                ),
                (
                    "source_wp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="solar_engine.wbsworkpackage",
                    ),
                ),
            ],
            options={
                "db_table": "solar_project_work_package",
                "ordering": ["stage", "order", "id"],
            },
        ),
    ]
