# Generated by Django 6.0.5 on 2026-10-05 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_materialmaster_gst_percentage_and_more"),
        ("solar_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectworkpackage",
            name="assigned_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solar_work_packages",
                to="core.vendor",
            ),
        ),
    ]
