# Generated by Django 6.0.5 on 2026-10-05 18:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_materialmaster_gst_percentage_and_more"),
        ("solar_engine", "0002_projectworkpackage_assigned_vendor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProgressEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=200)),
                ("progress_date", models.DateField()),
                (
                    "progress_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("skipped", "Skipped"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="field_progress/"
                    ),
                ),
                ("reporter_name", models.CharField(blank=True, max_length=150)),
                (
                    "source",
                    models.CharField(
                        choices=[("web", "ERP Web"), ("field", "Field Portal")],
                        default="web",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="solar_engine.projectbuild",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_progress_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="progress_entries",
                        to="solar_engine.projectstage",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_progress_entries",
                        to="core.vendor",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="progress_entries",
                        to="solar_engine.projectworkpackage",
                    ),
                ),
            ],
            options={
                "db_table": "solar_site_progress_entry",
                "ordering": ["-progress_date", "-created_at", "-id"],
            },
        ),
    ]
