# Generated by Django 6.0.5 on 2026-10-06 07:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_materialmaster_gst_percentage_and_more"),
        ("payments", "0002_vendorregistrationpayment"),
        (
            "purchase_orders",
            "0006_quotation_client_address_quotation_client_mobile_and_more",
        ),
        ("solar_engine", "0003_siteprogressentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("progress_threshold", "Progress reaches %"),
                            ("wp_completion", "Work package completed"),
                        ],
                        default="wp_completion",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_progress_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100"), max_digits=5
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "retention_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "payment_stage",
                    models.CharField(
                        choices=[
                            ("advance", "Advance"),
                            ("against_dispatch", "Against Dispatch"),
                            ("against_delivery", "Against Delivery"),
                            ("after_installation", "After Installation"),
                            ("retention", "Retention"),
                            ("final_payment", "Final Payment"),
                        ],
                        default="after_installation",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("eligible", "Eligible"),
                            ("invoiced", "Invoiced"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("on_hold", "On Hold"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("eligible_at", models.DateTimeField(blank=True, null=True)),
                ("invoiced_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_milestones",
                        to="solar_engine.projectbuild",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_milestones",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_milestones",
                        to="core.vendor",
                    ),
                ),
                (
                    "vendor_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solar_milestones",
                        to="payments.vendorpayment",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_milestones",
                        to="solar_engine.projectworkpackage",
                    ),
                ),
            ],
            options={
                "db_table": "solar_billing_milestone",
                "ordering": ["build", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HandoverCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=40, unique=True),
                ),
                ("site_name", models.CharField(blank=True, max_length=200)),
                ("scope_description", models.TextField(blank=True)),
                ("issued_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("issued", "Issued")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="handover_certificates/"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handover_certificates",
                        to="solar_engine.projectbuild",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_handover_certs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handover_certificates",
                        to="core.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "solar_handover_certificate",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
