# Generated by Django 6.0.5 on 2026-10-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_engine", "0004_billingmilestone_handovercertificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingmilestone",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("progress_threshold", "Progress reaches %"),
                    ("wp_completion", "Work package completed"),
                    (
                        "handover_certificate",
                        "On handover certificate (retention release)",
                    ),
                ],
                default="wp_completion",
                max_length=20,
            ),
        ),
    ]
