# Generated by Django 6.0.5 on 2026-10-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_engine", "0005_alter_billingmilestone_trigger_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprogressentry",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="siteprogressentry",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
