# Generated by Django 6.0.5 on 2026-10-06 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_materialmaster_gst_percentage_and_more"),
        ("solar_engine", "0006_siteprogressentry_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PunchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=40, unique=True)),
                ("site_name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("civil", "Civil"),
                            ("mechanical", "Mechanical"),
                            ("electrical", "Electrical"),
                            ("safety", "Safety"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                            ("verified", "Verified"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("raised_on", models.DateField()),
                ("target_date", models.DateField(blank=True, null=True)),
                ("resolved_on", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.FileField(blank=True, null=True, upload_to="punch_items/"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("raiser_name", models.CharField(blank=True, max_length=150)),
                (
                    "source",
                    models.CharField(
                        choices=[("web", "ERP Web"), ("field", "Field Portal")],
                        default="web",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punch_items",
                        to="solar_engine.projectbuild",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raised_punch_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="punch_items",
                        to="solar_engine.projectstage",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="punch_items",
                        to="core.vendor",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="punch_items",
                        to="solar_engine.projectworkpackage",
                    ),
                ),
            ],
            options={
                "db_table": "solar_punch_item",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="QualityInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=200)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("torque_check", "Torque check"),
                            ("megger_test", "Megger / insulation resistance"),
                            ("earthing_continuity", "Earthing continuity"),
                            ("iv_curve", "IV-curve tracing"),
                            ("pre_commissioning", "Pre-commissioning"),
                            ("general", "General inspection"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("inspection_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="quality_inspections/"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("reporter_name", models.CharField(blank=True, max_length=150)),
                (
                    "source",
                    models.CharField(
                        choices=[("web", "ERP Web"), ("field", "Field Portal")],
                        default="web",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="solar_engine.projectbuild",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="solar_engine.projectstage",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="core.vendor",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="solar_engine.projectworkpackage",
                    ),
                ),
            ],
            options={
                "db_table": "solar_quality_inspection",
                "ordering": ["-inspection_date", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="QualityCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("parameter", models.CharField(max_length=200)),
                ("spec", models.CharField(blank=True, max_length=120)),
                ("measured", models.CharField(blank=True, max_length=120)),
                ("unit", models.CharField(blank=True, max_length=40)),
                (
                    "result",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail"), ("na", "N/A")],
                        default="na",
                        max_length=10,
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=255)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="solar_engine.qualityinspection",
                    ),
                ),
            ],
            options={
                "db_table": "solar_quality_checkpoint",
                "ordering": ["order", "id"],
            },
        ),
    ]
