# Generated by Django 6.0.5 on 2026-10-06 18:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_engine", "0007_punchitem_qualityinspection_qualitycheckpoint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "build",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget",
                        to="solar_engine.projectbuild",
                    ),
                ),
            ],
            options={
                "db_table": "solar_project_budget",
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("cost_head", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("capex", "CapEx"), ("opex", "OpEx")],
                        default="capex",
                        max_length=10,
                    ),
                ),
                (
                    "budgeted_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "committed_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="solar_engine.projectbudget",
                    ),
                ),
            ],
            options={
                "db_table": "solar_budget_line",
                "ordering": ["order", "id"],
            },
        ),
    ]
