# Generated by Django 6.0.5 on 2026-10-08 08:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_projectplanner"),
        ("solar_engine", "0008_projectbudget_budgetline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectworkpackage",
            name="engagement_type",
            field=models.CharField(
                choices=[
                    ("milestone", "On milestones"),
                    (
                        "free_issue",
                        "Free-issue material (labour/machinery/installation only)",
                    ),
                ],
                default="milestone",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MaterialRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requisition_no", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("issued", "Issued"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("needed_by", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("raised_by_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_requisitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_requisitions",
                        to="core.vendor",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitions",
                        to="solar_engine.projectworkpackage",
                    ),
                ),
            ],
            options={
                "db_table": "solar_material_requisition",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialIssueSlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mis_no", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("acknowledged", "Acknowledged by vendor"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("issued_by_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_issue_slips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_issue_slips",
                        to="core.vendor",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_slips",
                        to="solar_engine.projectworkpackage",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_slips",
                        to="solar_engine.materialrequisition",
                    ),
                ),
            ],
            options={
                "db_table": "solar_material_issue_slip",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WorkPackageBom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("material_code", models.CharField(blank=True, max_length=60)),
                ("material_name", models.CharField(max_length=200)),
                ("specification", models.TextField(blank=True)),
                ("unit", models.CharField(default="Nos", max_length=40)),
                (
                    "bom_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "source_boq_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="solar_engine.projectboqitem",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_lines",
                        to="solar_engine.projectworkpackage",
                    ),
                ),
            ],
            options={
                "db_table": "solar_wp_bom",
                "ordering": ["work_package", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRequisitionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_code", models.CharField(blank=True, max_length=60)),
                ("material_name", models.CharField(max_length=200)),
                ("unit", models.CharField(default="Nos", max_length=40)),
                (
                    "quantity_requested",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="solar_engine.materialrequisition",
                    ),
                ),
                (
                    "bom_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisition_lines",
                        to="solar_engine.workpackagebom",
                    ),
                ),
            ],
            options={
                "db_table": "solar_material_requisition_line",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialIssueSlipLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_code", models.CharField(blank=True, max_length=60)),
                ("material_name", models.CharField(max_length=200)),
                ("unit", models.CharField(default="Nos", max_length=40)),
                (
                    "quantity_issued",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "issue_slip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="solar_engine.materialissueslip",
                    ),
                ),
                (
                    "bom_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_lines",
                        to="solar_engine.workpackagebom",
                    ),
                ),
            ],
            options={
                "db_table": "solar_material_issue_slip_line",
                "ordering": ["id"],
            },
        ),
    ]
