# Generated by Django 6.0.5 on 2026-10-08 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_projectplanner"),
        ("solar_engine", "0009_projectworkpackage_engagement_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rev_no", models.CharField(max_length=10)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="engineering_dms/"
                    ),
                ),
                ("change_note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted for review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("prepared_by_name", models.CharField(blank=True, max_length=150)),
                ("approved_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "solar_document_revision",
                "ordering": ["document", "sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="EngineeringDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_no", models.CharField(max_length=60, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("civil", "Civil"),
                            ("structural", "Structural"),
                            ("electrical", "Electrical"),
                            ("layout", "Layout / PV"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cad_drawing", "CAD Drawing"),
                            ("pvsyst_layout", "PVsyst Layout"),
                            ("sld", "Single Line Diagram (SLD)"),
                            ("datasheet", "Datasheet"),
                            ("statutory", "Statutory / Approval"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("for_discom", "Submitted for DISCOM"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "build",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engineering_documents",
                        to="solar_engine.projectbuild",
                    ),
                ),
                (
                    "current_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="solar_engine.documentrevision",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineering_documents",
                        to="core.projectmaster",
                    ),
                ),
            ],
            options={
                "db_table": "solar_engineering_document",
                "ordering": ["project", "discipline", "doc_no"],
            },
        ),
        migrations.AddField(
            model_name="documentrevision",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="solar_engine.engineeringdocument",
            ),
        ),
        migrations.CreateModel(
            name="StatutoryApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authority", models.CharField(max_length=120)),
                ("approval_type", models.CharField(max_length=150)),
                ("reference_no", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("resubmit", "Resubmit required"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_date", models.DateField(blank=True, null=True)),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("remark", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="statutory_approvals",
                        to="solar_engine.engineeringdocument",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statutory_approvals",
                        to="core.projectmaster",
                    ),
                ),
            ],
            options={
                "db_table": "solar_statutory_approval",
                "ordering": ["project", "-created_at", "-id"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="documentrevision",
            unique_together={("document", "rev_no")},
        ),
    ]
