# Generated by Django 6.0.5 on 2026-10-08 14:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_projectplanner"),
        ("solar_engine", "0010_documentrevision_engineeringdocument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubcontractWorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wo_no", models.CharField(max_length=40, unique=True)),
                (
                    "engagement_type",
                    models.CharField(
                        choices=[
                            ("milestone", "On milestones"),
                            (
                                "free_issue",
                                "Free-issue material (labour/machinery/installation only)",
                            ),
                        ],
                        default="milestone",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("scope_note", models.TextField(blank=True)),
                (
                    "contract_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "rate_basis",
                    models.CharField(
                        choices=[
                            ("per_wp", "Per work package"),
                            ("per_wp_wattage", "Per Watt (₹/Wp)"),
                            ("lumpsum", "Lump sum"),
                        ],
                        default="lumpsum",
                        max_length=20,
                    ),
                ),
                (
                    "rate_per_wp",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "retention_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders",
                        to="core.projectmaster",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="core.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "solar_subcontract_work_order",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SubcontractWorkOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="solar_engine.subcontractworkorder",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_order_lines",
                        to="solar_engine.projectworkpackage",
                    ),
                ),
            ],
            options={
                "db_table": "solar_subcontract_wo_line",
                "ordering": ["id"],
                "unique_together": {("work_order", "work_package")},
            },
        ),
    ]
