# Generated by Django 6.0.5 on 2026-10-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_engine", "0011_subcontractworkorder_subcontractworkorderline"),
    ]

    operations = [
        migrations.AddField(
            model_name="statutoryapproval",
            name="is_mandatory",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="statutoryapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("resubmit", "Resubmit required"),
                    ("waived", "Waived / N/A"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
