# Generated by Django 6.0.5 on 2026-10-09 12:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_projectplanner"),
        ("solar_engine", "0012_statutoryapproval_is_mandatory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_code", models.CharField(max_length=40, unique=True)),
                ("site_name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "capacity_mw",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_assessment", "In assessment"),
                            ("cleared", "Cleared"),
                            ("on_hold", "On hold"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solar_sites",
                        to="core.projectmaster",
                    ),
                ),
            ],
            options={
                "db_table": "solar_project_site",
                "ordering": ["project", "site_code"],
            },
        ),
        migrations.AddField(
            model_name="statutoryapproval",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statutory_approvals",
                to="solar_engine.projectsite",
            ),
        ),
        migrations.CreateModel(
            name="SiteAssessmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("cleared", "Cleared"),
                            ("rejected", "Rejected"),
                            ("waived", "Waived / N/A"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_items",
                        to="solar_engine.engineeringdocument",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="solar_engine.projectsite",
                    ),
                ),
            ],
            options={
                "db_table": "solar_site_assessment_item",
                "ordering": ["site", "id"],
            },
        ),
    ]
