# Generated by Django 6.0.5 on 2026-10-09 19:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_projectplanner"),
        ("solar_engine", "0013_projectsite_statutoryapproval_site_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCommercials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_rate_per_wp",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "overhead_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commercials",
                        to="core.projectmaster",
                    ),
                ),
            ],
            options={
                "db_table": "solar_project_commercials",
            },
        ),
    ]
