# Generated by Django 6.0.5 on 2026-10-09 20:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_projectplanner"),
        ("solar_engine", "0014_projectcommercials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceiptNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grn_no", models.CharField(max_length=40, unique=True)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                ("consignment_ref", models.CharField(blank=True, max_length=120)),
                ("received_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("received_by_name", models.CharField(blank=True, max_length=150)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods_receipts",
                        to="core.projectmaster",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipts",
                        to="solar_engine.projectsite",
                    ),
                ),
            ],
            options={
                "db_table": "solar_goods_receipt_note",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_code", models.CharField(blank=True, max_length=60)),
                ("material_name", models.CharField(max_length=200)),
                ("unit", models.CharField(default="Nos", max_length=40)),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("damaged", "Damaged"),
                            ("short", "Short supply"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("serial_numbers", models.TextField(blank=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="solar_engine.goodsreceiptnote",
                    ),
                ),
            ],
            options={
                "db_table": "solar_goods_receipt_line",
                "ordering": ["id"],
            },
        ),
    ]
