# Generated by Django 6.0.5 on 2026-10-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_materialmaster_gst_percentage_and_more"),
        (
            "purchase_orders",
            "0006_quotation_client_address_quotation_client_mobile_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="core.projectmaster",
            ),
        ),
    ]
